// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DataBaseAccess;

namespace SEP3_DB_Server.Migrations
{
    [DbContext(typeof(SEP_DBContext))]
    [Migration("20211102181552_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("SEP3_DB_Server.Models.Spike", b =>
                {
                    b.Property<string>("snor")
                        .HasColumnType("TEXT");

                    b.HasKey("snor");

                    b.ToTable("Spikes");
                });
#pragma warning restore 612, 618
        }
    }
}
