// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDBserverAPI.DataAccess;

namespace SEP3_DB_Server.Migrations
{
    [DbContext(typeof(SEP_DBContext))]
    partial class SEP_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("WebDBserverAPI.Models.Spike", b =>
                {
                    b.Property<string>("SpikeName")
                        .HasColumnType("TEXT");

                    b.HasKey("SpikeName");

                    b.ToTable("Spikes");
                });
#pragma warning restore 612, 618
        }
    }
}
