// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEP3_DB_Server.DataAccess;

namespace SEP3_DB_Server.Migrations
{
    [DbContext(typeof(SEP_DBContext))]
    partial class SEP_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("SEP3_DB_Server.Models.Snor", b =>
                {
                    b.Property<string>("snor")
                        .HasColumnType("TEXT");

                    b.HasKey("snor");

                    b.ToTable("Snors");
                });
#pragma warning restore 612, 618
        }
    }
}
